CREATE TABLE IF NOT EXISTS "a_Arena" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "matchState"                     BYTEA,
    "matchType"                      BYTEA,
    "maximizeShipTL"                 BYTEA,
    "maxShipTL"                      BYTEA,
    "name"                           TEXT,
    "opponentDesignsOk"              BYTEA,
    "password"                       TEXT,
    "shipDesign"                     BYTEA,
    "designIsSc"                     BYTEA,
    "spawnCrew"                      BYTEA,
    "spawnOfficer"                   BYTEA,
    "spawnPassengers"                BYTEA,
    "spawnTroops"                    BYTEA,
    "spawnVehicles"                  BYTEA,
    "teamShips"                      BYTEA,
    "team1Ships"                     BYTEA,
    "team2ships"                     BYTEA,
    "idp"                            BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Arena_idp" ON "a_Arena" ("idp");

CREATE TABLE IF NOT EXISTS "a_Bd" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "damageHistory"                  BYTEA,
    "capacitor"                      DOUBLE PRECISION,

    "capitol"                        BIGINT,
    "cityName"                       TEXT,
    "citizenDNA"                     BYTEA,
    "cargo"                          BYTEA,
    "damage"                         BYTEA,
    "bank"                           DOUBLE PRECISION,

    "industry"                       INTEGER,
    "qual"                           BYTEA,
    "qop"                            BYTEA,
    "mfgproc"                        BYTEA,
    "systems"                        BYTEA,
    "shield"                         DOUBLE PRECISION,
    "games"                          BYTEA,
    "baySetting"                     BYTEA,
    "designRpt"                      BYTEA,
    "airPressures"                   BYTEA,
    "doorStates"                     BYTEA,
    "landingSystems"                 BYTEA,
    "launchers"                      BYTEA,
    "lifts"                          BYTEA,
    "roomLights"                     BYTEA,
    "transporters"                   BYTEA,
    "turretPos"                      BYTEA,
    "reportHist"                     BYTEA,
    "reportTime"                     BIGINT,
    "lastVisit"                      BYTEA,
    "scFactory"                      BYTEA,
    "media"                          BYTEA,
    "broker"                         BYTEA,
    "idp"                            BIGINT,
    "designId"                       BIGINT,
    "cityPop"                        BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Bd_idp" ON "a_Bd" ("idp");

CREATE TABLE IF NOT EXISTS "a_CitCharacter" (
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_CitCharacter_idp" ON "a_CitCharacter" ("idp");

CREATE TABLE IF NOT EXISTS "a_CitCop" (
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_CitCop_idp" ON "a_CitCop" ("idp");

CREATE TABLE IF NOT EXISTS "a_CitCrew" (
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_CitCrew_idp" ON "a_CitCrew" ("idp");

CREATE TABLE IF NOT EXISTS "a_CitIndigenous" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "damageHistory"                  BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER,
    "lineage"                        INTEGER,
    "ship"                           BIGINT,
    "orders"                         BYTEA,
    "posture"                        INTEGER,
    "inv"                            BYTEA,
    "homeworld"                      BIGINT,
    "interlocutor"                   BIGINT,
    "role"                           INTEGER,
    "idp"                            BIGINT
);

CREATE INDEX IF NOT EXISTS "ix_a_CitIndigenous_idp" ON "a_CitIndigenous" ("idp");

CREATE TABLE IF NOT EXISTS "a_CitOfficer" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "damageHistory"                  BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "stationId"                      BIGINT,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "lineage"                        INTEGER,
    "ship"                           BYTEA,
    "orders"                         INTEGER,
    "posture"                        BYTEA,
    "inv"                            BYTEA,
    "log"                            BYTEA,
    "logtime"                        BIGINT,
    "xp"                             BIGINT,
    "sectorId"                       BIGINT,
    "sectorName"                     TEXT,
    "systemId"                       BIGINT,
    "systemName"                     TEXT,
    "worldId"                        BIGINT,
    "worldName"                      TEXT,
    "galaxy"                         TEXT,
    "contactTime"                    BIGINT,
    "con"                            BYTEA,
    "homesick"                       BYTEA,
    "homesickTime"                   BIGINT,
    "idp"                            BIGINT,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_CitOfficer_idp" ON "a_CitOfficer" ("idp");

CREATE TABLE IF NOT EXISTS "a_CitPassenger" (
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_CitPassenger_idp" ON "a_CitPassenger" ("idp");

CREATE TABLE IF NOT EXISTS "a_CitTroop" (
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_CitTroop_idp" ON "a_CitTroop" ("idp");

CREATE TABLE IF NOT EXISTS "a_CitWorker" (
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_CitWorker_idp" ON "a_CitWorker" ("idp");

CREATE TABLE IF NOT EXISTS "a_City" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "satis"                          BYTEA,
    "population"                     BYTEA,
    "meal"                           BYTEA,
    "name"                           TEXT,
    "stock"                          BYTEA,
    "flags"                          BYTEA,
    "reportHist"                     BYTEA,
    "decay"                          BYTEA,
    "log"                            BYTEA,
    "allegEmpire"                    BYTEA,
    "allegLevel"                     BYTEA,
    "bsCurrentBalance"               DOUBLE PRECISION,
    "bsExCommission"                 DOUBLE PRECISION,
    "bsExRewards"                    DOUBLE PRECISION,
    "bsExRnD"                        DOUBLE PRECISION,
    "bsExTribute"                    DOUBLE PRECISION,
    "bsExWithdrawal"                 DOUBLE PRECISION,
    "bsExWorks"                      DOUBLE PRECISION,
    "bsInConfiscated"                DOUBLE PRECISION,
    "bsInDeposit"                    DOUBLE PRECISION,
    "bsInIncomeTax"                  DOUBLE PRECISION,
    "bsInLevy"                       DOUBLE PRECISION,
    "bsInRnD"                        DOUBLE PRECISION,
    "bsInSalesTax"                   DOUBLE PRECISION,
    "bsInSubsidyTax"                 DOUBLE PRECISION,
    "lastTribute"                    DOUBLE PRECISION,
    "manproc"                        BYTEA,
    "shields"                        DOUBLE PRECISION,
    "troomstates"                    BYTEA,
    "weapons"                        BYTEA,
    "games"                          BYTEA,
    "situations"                     BYTEA,
    "citizenDNA"                     BYTEA,
    "bankBalance"                    DOUBLE PRECISION,
    "bankExConfiscated"              DOUBLE PRECISION,
    "bankExEmigrate"                 DOUBLE PRECISION,
    "bankExLoans"                    DOUBLE PRECISION,
    "bankExPurchases"                DOUBLE PRECISION,
    "bankExRewards"                  DOUBLE PRECISION,
    "bankExRnD"                      DOUBLE PRECISION,
    "bankExSalary"                   DOUBLE PRECISION,
    "bankExWholesale"                DOUBLE PRECISION,
    "bankExWithdrawal"               DOUBLE PRECISION,
    "bankInImmigrate"                DOUBLE PRECISION,
    "bankInLoans"                    DOUBLE PRECISION,
    "bankInMfg"                      DOUBLE PRECISION,
    "bankInRnD"                      DOUBLE PRECISION,
    "bankInSalary"                   DOUBLE PRECISION,
    "bankInSales"                    DOUBLE PRECISION,
    "bankInWholesale"                DOUBLE PRECISION,
    "developments"                   BYTEA,
    "garrisonTroops"                 BYTEA,
    "lastVisit"                      BYTEA,
    "idp"                            BIGINT,
    "industries"                     BYTEA,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER,
    "capitol"                        BIGINT
);

CREATE INDEX IF NOT EXISTS "ix_a_City_idp" ON "a_City" ("idp");

CREATE TABLE IF NOT EXISTS "a_DesignEnv" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "archid"                         BIGINT,
    "designid"                       BIGINT,
    "ownerid"                        BIGINT,
    "designname"                     TEXT,
    "studioid"                       BIGINT,
    "modified"                       BYTEA,
    "archname"                       TEXT,
    "designMode"                     BYTEA,
    "building"                       BIGINT,
    "idp"                            BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_DesignEnv_idp" ON "a_DesignEnv" ("idp");

CREATE TABLE IF NOT EXISTS "a_Designer" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "archid"                         BIGINT,
    "ownerid"                        BIGINT,
    "design"                         BYTEA,
    "studioid"                       BIGINT,
    "modified"                       BYTEA,
    "archname"                       TEXT,
    "designMode"                     BYTEA,
    "viewOnly"                       INTEGER,
    "idp"                            BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Designer_idp" ON "a_Designer" ("idp");

CREATE TABLE IF NOT EXISTS "a_DesignPlane" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "gravity"                        DOUBLE PRECISION,
    "onBits"                         BYTEA,
    "owner"                          BYTEA,
    "render"                         BYTEA,
    "roomid"                         BIGINT,
    "roomMode"                       BYTEA,
    "inc"                            DOUBLE PRECISION,
    "rad"                            DOUBLE PRECISION,
    "idp"                            BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_DesignPlane_idp" ON "a_DesignPlane" ("idp");

CREATE TABLE IF NOT EXISTS "a_Galaxy" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "galaxy"                         TEXT,
    "idp"                            BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Galaxy_idp" ON "a_Galaxy" ("idp");

CREATE TABLE IF NOT EXISTS "a_Item" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "item"                           BYTEA,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "ownerId"                        BIGINT,
    "ownerName"                      TEXT,
    "ownerEmpire"                    BYTEA,
    "staticDisplay"                  BYTEA,
    "idp"                            BIGINT,
    "cid"                            BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Item_idp" ON "a_Item" ("idp");

CREATE TABLE IF NOT EXISTS "a_Person" (

    "id"                             BIGINT
        GENERATED BY DEFAULT AS IDENTITY
            (START WITH 512 MINVALUE 512 MAXVALUE 4294967295 NO CYCLE)
        PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "damageHistory"                  BYTEA,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "stationId"                      BIGINT,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "hunger"                         INTEGER,
    "autoEat"                        INTEGER,
    "seatIndex"                      INTEGER,
    "minsToFullGrown"                INTEGER,
    "orders"                         INTEGER,
    "posture"                        BYTEA,
    "bank"                           DOUBLE PRECISION,
    "loan"                           DOUBLE PRECISION,
    "agentBits"                      BYTEA,
    "arenaEntered"                   BIGINT,
    "arenaExitLocX"                  DOUBLE PRECISION,
    "arenaExitLocY"                  DOUBLE PRECISION,
    "arenaExitLocZ"                  DOUBLE PRECISION,
    "arenaExitParent"                BIGINT,
    "arenaShipDesign"                BIGINT,
    "arenaDesignIsSc"                INTEGER,
    "usepos"                         BYTEA,
    "usesub"                         BYTEA,

    "social"                         INTEGER,
    "xp"                             BIGINT,
    "worms"                          BYTEA,
    "designpass"                     BYTEA,
    "spawncity"                      BIGINT,
    "spawnCityName"                  TEXT,
    "spawnGalaxy"                    BIGINT,
    "spawnx"                         DOUBLE PRECISION,
    "spawny"                         DOUBLE PRECISION,
    "spawnship"                      BIGINT,
    "spawnShipIsPrivate"             INTEGER,
    "spawnShipName"                  TEXT,
    "berthType"                      INTEGER,
    "inv"                            BYTEA,
    "seaChest"                       BYTEA,
    "rewards"                        BYTEA,
    "isonline"                       INTEGER,
    "lineage"                        INTEGER,
    "dad"                            BIGINT,
    "mom"                            BIGINT,
    "accountInactive"                INTEGER,
    "con"                            BYTEA,
    "jobs"                           BYTEA,
    "memory"                         BYTEA,
    "stats"                          BYTEA,
    "log"                            BYTEA,
    "logtime"                        BIGINT,
    "mappos"                         BYTEA,
    "timeOnlineSecs"                 BIGINT NOT NULL DEFAULT 0,
    "idp"                            BIGINT,

    "selfie"                         BYTEA
);

CREATE INDEX IF NOT EXISTS "ix_a_Person_idp" ON "a_Person" ("idp");

CREATE TABLE IF NOT EXISTS "a_Sc" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "damageHistory"                  BYTEA,
    "state"                          INTEGER,
    "accessPolicy"                   BYTEA,
    "pilotUpPolicy"                  BYTEA,
    "shieldPolicy"                   BYTEA,
    "shieldFuelPolicy"               BYTEA,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "throttle"                       DOUBLE PRECISION,
    "throttleLateral"                DOUBLE PRECISION,
    "throttleLong"                   DOUBLE PRECISION,
    "throttleVertical"               DOUBLE PRECISION,
    "ownerId"                        BIGINT,
    "ownerName"                      TEXT,
    "durEngine"                      DOUBLE PRECISION,
    "skewEngine"                     DOUBLE PRECISION,
    "fuel"                           DOUBLE PRECISION,
    "fuelqual"                       DOUBLE PRECISION,
    "rotSpeeds"                      DOUBLE PRECISION,
    "actBits"                        BYTEA,
    "capacitor"                      DOUBLE PRECISION,
    "route"                          BYTEA,
    "cargo"                          BYTEA,
    "damage"                         BYTEA,
    "roster"                         BYTEA,
    "bank"                           DOUBLE PRECISION,
    "bankSubsidyTax"                 DOUBLE PRECISION,
    "systems"                        BYTEA,
    "shieldFront"                    DOUBLE PRECISION,
    "shieldBack"                     DOUBLE PRECISION,
    "shieldLeft"                     DOUBLE PRECISION,
    "shieldRight"                    DOUBLE PRECISION,
    "shieldTop"                      DOUBLE PRECISION,
    "shieldBottom"                   DOUBLE PRECISION,
    "powerPlantShunts"               BYTEA,
    "techLevel"                      BYTEA,
    "whereMade"                      TEXT,
    "mission"                        BYTEA,
    "games"                          BYTEA,
    "repairSecs"                     DOUBLE PRECISION,
    "baySetting"                     BYTEA,
    "ratdna"                         BYTEA,
    "monster"                        BYTEA,
    "switches"                       BYTEA,
    "designRpt"                      BYTEA,
    "airPressures"                   BYTEA,
    "doorStates"                     BYTEA,
    "ftlDrives"                      BYTEA,
    "landingGear"                    BYTEA,
    "landingSystems"                 BYTEA,
    "launchers"                      BYTEA,
    "lifts"                          BYTEA,
    "roomLights"                     BYTEA,
    "transporters"                   BYTEA,
    "turretPos"                      BYTEA,
    "idp"                            BIGINT,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Sc_idp" ON "a_Sc" ("idp");

CREATE TABLE IF NOT EXISTS "a_Sector" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "idp"                            BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Sector_idp" ON "a_Sector" ("idp");

CREATE TABLE IF NOT EXISTS "a_SolarSystem" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "wormholes"                      BYTEA,
    "exploredBy"                     BYTEA,
    "scannedBy"                      BYTEA,
    "lastVisit"                      BYTEA,
    "lastOfficerVisit"               BYTEA,

    "genHab"                         INTEGER,

    "genSeed"                        BIGINT,
    "lastPirateStation"              BYTEA,
    "idp"                            BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_SolarSystem_idp" ON "a_SolarSystem" ("idp");

CREATE TABLE IF NOT EXISTS "a_SpaceShip" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "state"                          INTEGER,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "damageHistory"                  BYTEA,
    "idDesign"                       BYTEA,
    "accessPolicy"                   BYTEA,
    "pilotUpPolicy"                  BYTEA,
    "shieldPolicy"                   BYTEA,
    "shieldFuelPolicy"               BYTEA,
    "switches2"                      BYTEA,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "throttle"                       DOUBLE PRECISION,
    "throttleLateral"                DOUBLE PRECISION,
    "throttleLong"                   DOUBLE PRECISION,
    "throttleVertical"               DOUBLE PRECISION,
    "wormCommit"                     BYTEA,
    "ownerId"                        BIGINT,
    "ownerName"                      TEXT,
    "durEngine"                      DOUBLE PRECISION,
    "skewEngine"                     DOUBLE PRECISION,
    "fuel"                           DOUBLE PRECISION,
    "fuelqual"                       DOUBLE PRECISION,
    "rotSpeeds"                      DOUBLE PRECISION,
    "actBits"                        BYTEA,
    "capacitor"                      DOUBLE PRECISION,
    "doors"                          BYTEA,
    "doorstates"                     BYTEA,
    "route"                          BYTEA,
    "cargo"                          BYTEA,
    "damage"                         BYTEA,
    "roster"                         BYTEA,
    "bank"                           DOUBLE PRECISION,
    "bankSubsidyTax"                 DOUBLE PRECISION,
    "systems"                        BYTEA,
    "shieldFront"                    DOUBLE PRECISION,
    "shieldBack"                     DOUBLE PRECISION,
    "shieldLeft"                     DOUBLE PRECISION,
    "shieldRight"                    DOUBLE PRECISION,
    "shieldTop"                      DOUBLE PRECISION,
    "shieldBottom"                   DOUBLE PRECISION,
    "troomstates"                    BYTEA,
    "powerPlantShunts"               BYTEA,
    "techLevel"                      BYTEA,
    "whereMade"                      TEXT,
    "airPressure"                    BYTEA,
    "mission"                        BYTEA,
    "games"                          BYTEA,
    "repairSecs"                     DOUBLE PRECISION,
    "baySetting"                     BYTEA,
    "ratdna"                         BYTEA,
    "ftlSetting"                     BYTEA,
    "monster"                        BYTEA,
    "idp"                            BIGINT,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_SpaceShip_idp" ON "a_SpaceShip" ("idp");

CREATE TABLE IF NOT EXISTS "a_Star" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "specType"                       BYTEA,
    "specDec"                        BYTEA,
    "specSize"                       BYTEA,
    "radius"                         DOUBLE PRECISION,
    "orbit"                          DOUBLE PRECISION,
    "habZone"                        DOUBLE PRECISION,
    "orbitZones"                     BYTEA,
    "idp"                            BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Star_idp" ON "a_Star" ("idp");

CREATE TABLE IF NOT EXISTS "a_Teleporter" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "node"                           BYTEA,
    "maxRange"                       DOUBLE PRECISION,
    "spotType"                       BYTEA,
    "teleporters"                    BYTEA,
    "idp"                            BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Teleporter_idp" ON "a_Teleporter" ("idp");

CREATE TABLE IF NOT EXISTS "a_Universe" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "idp"                            BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_Universe_idp" ON "a_Universe" ("idp");

CREATE TABLE IF NOT EXISTS "a_WorldGasGiant" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "orbitRadius"                    BYTEA,
    "orbitZone"                      BYTEA,
    "claimedBy"                      BYTEA,
    "claimLon"                       BYTEA,
    "claimLat"                       BYTEA,
    "claimId"                        BIGINT,
    "claimName"                      TEXT,
    "claimTime"                      BIGINT,
    "geoFeatures"                    BYTEA,
    "atmDensity"                     BYTEA,
    "atmType"                        BYTEA,
    "radius"                         DOUBLE PRECISION,
    "dna"                            BYTEA,
    "fauna"                          BYTEA,
    "flora"                          BYTEA,
    "terrain"                        BYTEA,
    "idp"                            BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER,
    "coreRadius"                     BYTEA
);

CREATE INDEX IF NOT EXISTS "ix_a_WorldGasGiant_idp" ON "a_WorldGasGiant" ("idp");

CREATE TABLE IF NOT EXISTS "a_WorldGlobe" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "orbitRadius"                    BYTEA,
    "orbitZone"                      BYTEA,
    "captId"                         BIGINT,
    "captName"                       TEXT,

    "claimedBy"                      BIGINT,

    "claimLon"                       DOUBLE PRECISION,

    "claimLat"                       DOUBLE PRECISION,
    "claimId"                        BIGINT,
    "claimName"                      TEXT,
    "claimTime"                      BIGINT,
    "geoFeatures"                    BYTEA,
    "atmDensity"                     BYTEA,
    "atmType"                        BYTEA,
    "radius"                         DOUBLE PRECISION,
    "dna"                            BYTEA,
    "fauna"                          BYTEA,
    "flora"                          BYTEA,
    "terrain"                        BYTEA,
    "water"                          BYTEA,
    "village"                        BYTEA,
    "idp"                            BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_WorldGlobe_idp" ON "a_WorldGlobe" ("idp");

CREATE TABLE IF NOT EXISTS "a_WorldRing" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "orbitRadius"                    BYTEA,
    "orbitZone"                      BYTEA,
    "idp"                            BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_WorldRing_idp" ON "a_WorldRing" ("idp");

CREATE TABLE IF NOT EXISTS "a_WorldRingSection" (
    "id"                             BIGINT PRIMARY KEY,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "orbitRadius"                    BYTEA,
    "orbitZone"                      BYTEA,
    "captId"                         BIGINT,
    "captName"                       TEXT,
    "claimedBy"                      BYTEA,
    "claimLon"                       BYTEA,
    "claimLat"                       BYTEA,
    "claimId"                        BIGINT,
    "claimName"                      TEXT,
    "claimTime"                      BIGINT,
    "geoFeatures"                    BYTEA,
    "atmDensity"                     BYTEA,
    "atmType"                        BYTEA,
    "dna"                            BYTEA,
    "fauna"                          BYTEA,
    "flora"                          BYTEA,

    "sectionIndex"                   INTEGER,
    "terrain"                        BYTEA,
    "water"                          BYTEA,
    "village"                        BYTEA,
    "idp"                            BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_a_WorldRingSection_idp" ON "a_WorldRingSection" ("idp");

CREATE TABLE IF NOT EXISTS "b_ConstructionComponent" (
    "id"                             BIGINT PRIMARY KEY,
    "idcp"                           BYTEA,
    "idc"                            BYTEA,
    "consumes"                       BYTEA,
    "ide"                            BYTEA,
    "lvl"                            BYTEA,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_b_ConstructionComponent_idp" ON "b_ConstructionComponent" ("idp");

CREATE TABLE IF NOT EXISTS "b_ConstructionProcess" (
    "id"                             BIGINT PRIMARY KEY,
    "name"                           TEXT,
    "idi"                            BYTEA,
    "sitePrep"                       BYTEA,
    "stackLimit"                     BYTEA,
    "idt"                            BYTEA,
    "buildRadius"                    BYTEA,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_b_ConstructionProcess_idp" ON "b_ConstructionProcess" ("idp");

CREATE TABLE IF NOT EXISTS "b_Industry" (
    "id"                             BIGINT PRIMARY KEY,
    "name"                           TEXT,
    "pop"                            BYTEA,
    "emp"                            BYTEA,
    "storage"                        BYTEA,
    "buildRule"                      BYTEA,
    "capacitor"                      DOUBLE PRECISION,
    "structure"                      BYTEA,
    "field"                          BYTEA,
    "arena"                          BYTEA,
    "auditorium"                     BYTEA,
    "battery"                        BYTEA,
    "cargoStorage"                   BYTEA,
    "generator"                      BYTEA,
    "guardPost"                      BYTEA,
    "homeLarge"                      BYTEA,
    "homeMedium"                     BYTEA,
    "homeSmall"                      BYTEA,
    "livestockPost"                  BYTEA,
    "lounge"                         BYTEA,
    "note"                           BYTEA,
    "office"                         BYTEA,
    "parkGround"                     BYTEA,
    "parkSpace"                      BYTEA,
    "parkWater"                      BYTEA,
    "store"                          BYTEA,
    "sensor"                         BYTEA,
    "shield"                         DOUBLE PRECISION,
    "shop"                           BYTEA,
    "surgery"                        BYTEA,
    "transporter"                    BYTEA,
    "turret"                         BYTEA,
    "vehicleLauncher"                BYTEA,
    "vehicleRecovery"                BYTEA,
    "weaponBay"                      BYTEA,
    "doesWhat"                       BYTEA,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_b_Industry_idp" ON "b_Industry" ("idp");

CREATE TABLE IF NOT EXISTS "b_ManufacturingComponent" (
    "id"                             BIGINT PRIMARY KEY,
    "idmp"                           BYTEA,
    "idc"                            BYTEA,
    "consumed"                       BYTEA,
    "ide"                            BYTEA,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_b_ManufacturingComponent_idp" ON "b_ManufacturingComponent" ("idp");

CREATE TABLE IF NOT EXISTS "b_ManufacturingProcess" (
    "id"                             BIGINT PRIMARY KEY,
    "name"                           TEXT,
    "idc"                            BYTEA,
    "idi"                            BYTEA,
    "qty"                            BYTEA,
    "labor"                          BYTEA,
    "nat"                            BYTEA,
    "craft"                          BYTEA,
    "isdefault"                      BYTEA,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_b_ManufacturingProcess_idp" ON "b_ManufacturingProcess" ("idp");

CREATE TABLE IF NOT EXISTS "g_Empire" (
    "name"                           TEXT,

    "announcements"                  TEXT,
    "immig"                          BYTEA,
    "cityDebt"                       BYTEA,
    "flag"                           BYTEA,
    "capitalCity"                    BYTEA,
    "capitalDNA"                     BYTEA,
    "rewCapBase"                     BYTEA,
    "rewCapCapital"                  BYTEA,
    "rewCapCapitalSector"            BYTEA,
    "rewCapCity"                     BYTEA,
    "rewCapSpaceport"                BYTEA,
    "rewCapSpaceship"                BYTEA,
    "rewCapStarship"                 BYTEA,
    "rewDmgSpaceport"                BYTEA,
    "rewDmgSpaceship"                BYTEA,
    "rewDmgStarShip"                 BYTEA,
    "rewDiscHabitable"               BYTEA,
    "rewDiscWorm"                    BYTEA,
    "rewKillEnemy"                   BYTEA,
    "rewSalary"                      BYTEA,
    "rewSpotCity"                    BYTEA,
    "rewSpotEnemy"                   BYTEA,
    "taxIncome"                      BYTEA,
    "taxSales"                       BYTEA,
    "taxSubsidy"                     BYTEA,
    "defaultStance"                  BYTEA,
    "stance"                         BYTEA,
    "theme"                          BYTEA,
    "commerce"                       BYTEA,
    "citizens"                       BYTEA,
    "cities"                         BYTEA,
    "capturemsg"                     BYTEA,
    "rightToFound"                   BYTEA,
    "fOffice"                        BYTEA,
    "trespass"                       BYTEA,

    "contrailHue"                    INTEGER,

    "contrailSat"                    INTEGER,
    "joinPass"                       BYTEA,
    "role"                           INTEGER,
    "zoneBuildPolicy"                BYTEA,
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_g_Empire_idp" ON "g_Empire" ("idp");

CREATE TABLE IF NOT EXISTS "n_BdDesign" (
    "name"                           TEXT,
    "ida"                            BYTEA,
    "archname"                       TEXT,
    "state"                          INTEGER,
    "textures"                       BYTEA,
    "parts"                          BYTEA,
    "modules"                        BYTEA,
    "structure"                      BYTEA,
    "arenas"                         BYTEA,
    "armor"                          BYTEA,
    "auditoriums"                    BYTEA,
    "bays"                           BYTEA,
    "capacitor"                      DOUBLE PRECISION,
    "hold"                           BYTEA,
    "homesLarge"                     BYTEA,
    "homesMedium"                    BYTEA,
    "homesSmall"                     BYTEA,
    "lifeSupport"                    BYTEA,
    "lounges"                        BYTEA,
    "offices"                        BYTEA,
    "powerPlant"                     BYTEA,
    "sensors"                        BYTEA,
    "shields"                        DOUBLE PRECISION,
    "shops"                          BYTEA,
    "stores"                         BYTEA,
    "hullVolume"                     BYTEA,
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_n_BdDesign_idp" ON "n_BdDesign" ("idp");

CREATE TABLE IF NOT EXISTS "n_BdExchange" (
    "state"                          INTEGER,
    "canCopy"                        BYTEA,
    "canView"                        BYTEA,
    "empire"                         BYTEA,
    "minStance"                      BYTEA,
    "price"                          BYTEA,
    "useOnce"                        BYTEA,
    "report"                         BYTEA,
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_n_BdExchange_idp" ON "n_BdExchange" ("idp");

CREATE TABLE IF NOT EXISTS "n_Building" (
    "id"                             BIGINT PRIMARY KEY,
    "name"                           TEXT,
    "ida"                            BYTEA,
    "archname"                       TEXT,
    "state"                          INTEGER,
    "empireids"                      BYTEA,
    "iid"                            BIGINT,
    "module"                         BYTEA,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_n_Building_idp" ON "n_Building" ("idp");

CREATE TABLE IF NOT EXISTS "n_DetailType" (
    "id"                             BIGINT PRIMARY KEY,
    "name"                           TEXT,
    "dscr"                           BYTEA,
    "nameB"                          BYTEA,
    "dscrB"                          BYTEA,
    "bridgeOk"                       BYTEA,
    "crew"                           BYTEA,
    "place"                          BYTEA,
    "techLevel"                      BYTEA,
    "wt"                             BYTEA,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_n_DetailType_idp" ON "n_DetailType" ("idp");

CREATE TABLE IF NOT EXISTS "n_RoomType" (
    "id"                             BIGINT PRIMARY KEY,
    "name"                           TEXT,
    "dscr"                           BYTEA,
    "nameB"                          BYTEA,
    "dscrB"                          BYTEA,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_n_RoomType_idp" ON "n_RoomType" ("idp");

CREATE TABLE IF NOT EXISTS "n_ScDesign" (
    "name"                           TEXT,
    "ida"                            BYTEA,
    "archname"                       TEXT,
    "state"                          INTEGER,
    "textures"                       BYTEA,
    "parts"                          BYTEA,
    "modules"                        BYTEA,
    "stationOrient"                  BYTEA,
    "streamline"                     BYTEA,
    "structure"                      BYTEA,
    "techLevelMin"                   BYTEA,
    "armor"                          BYTEA,
    "bays"                           BYTEA,
    "capacitor"                      DOUBLE PRECISION,
    "cryoBerths"                     BYTEA,
    "ftlDrives"                      BYTEA,
    "fuel"                           DOUBLE PRECISION,
    "hold"                           BYTEA,
    "lifeSupport"                    BYTEA,
    "maneuverDrive"                  BYTEA,
    "powerPlant"                     BYTEA,
    "sensors"                        BYTEA,
    "shields"                        DOUBLE PRECISION,
    "hullVolume"                     BYTEA,
    "pirateOk"                       BYTEA,
    "techLevel"                      BYTEA,
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_n_ScDesign_idp" ON "n_ScDesign" ("idp");

CREATE TABLE IF NOT EXISTS "n_ScExchange" (
    "state"                          INTEGER,
    "canCopy"                        BYTEA,
    "canView"                        BYTEA,
    "empire"                         BYTEA,
    "minStance"                      BYTEA,
    "price"                          BYTEA,
    "useOnce"                        BYTEA,
    "report"                         BYTEA,
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "name"                           TEXT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_n_ScExchange_idp" ON "n_ScExchange" ("idp");

CREATE TABLE IF NOT EXISTS "n_SpaceShip" (
    "id"                             BIGINT PRIMARY KEY,
    "name"                           TEXT,
    "ida"                            BYTEA,
    "streamline"                     BYTEA,
    "armor"                          BYTEA,
    "state"                          INTEGER,
    "archname"                       TEXT,
    "empireids"                      BYTEA,
    "techLevelMin"                   BYTEA,
    "baymods"                        BYTEA,
    "cncmod"                         BYTEA,
    "ftlmod"                         BYTEA,
    "hullmod"                        BYTEA,
    "lifemod"                        BYTEA,
    "drivemod"                       BYTEA,
    "powermod"                       BYTEA,
    "sensormod"                      BYTEA,
    "shieldmod"                      DOUBLE PRECISION,
    "transportmods"                  BYTEA,
    "accel"                          BYTEA,
    "crewBerths"                     BYTEA,
    "hullVolume"                     BYTEA,
    "officerBerths"                  BYTEA,
    "passBerths"                     BYTEA,
    "pirateStructure"                BYTEA,
    "structure"                      BYTEA,
    "techLevel"                      BYTEA,
    "troopBerths"                    BYTEA,
    "turrets"                        BYTEA,
    "weaponBays"                     BYTEA,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_n_SpaceShip_idp" ON "n_SpaceShip" ("idp");

CREATE TABLE IF NOT EXISTS "z_Specie" (
    "name"                           TEXT,
    "whenNamed"                      BYTEA,
    "whoNamed"                       BYTEA,
    "id"                             BIGINT PRIMARY KEY,
    "idp"                            BIGINT,
    "locX"                           DOUBLE PRECISION,
    "locY"                           DOUBLE PRECISION,
    "locZ"                           DOUBLE PRECISION,
    "rotX"                           DOUBLE PRECISION,
    "rotY"                           DOUBLE PRECISION,
    "rotZ"                           DOUBLE PRECISION,
    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT,
    "timeTick"                       BIGINT,
    "timeTock"                       BIGINT,
    "timeDeath"                      BIGINT,
    "allegiance"                     BIGINT,
    "arenaTeam"                      INTEGER,
    "conditions"                     BYTEA,
    "hunger"                         INTEGER,
    "seatIndex"                      INTEGER,
    "hp"                             INTEGER,
    "sex"                            INTEGER,
    "dna"                            BYTEA,
    "islefty"                        INTEGER,
    "pose"                           INTEGER,
    "whichConsole"                   INTEGER,
    "atRest"                         INTEGER,
    "vecX"                           DOUBLE PRECISION,
    "vecY"                           DOUBLE PRECISION,
    "vecZ"                           DOUBLE PRECISION,
    "stamina"                        INTEGER,
    "minsToFullGrown"                INTEGER
);

CREATE INDEX IF NOT EXISTS "ix_z_Specie_idp" ON "z_Specie" ("idp");

CREATE TABLE IF NOT EXISTS "g_EmpireOffice" (
    "empire_id"                      BIGINT NOT NULL,
    "avatar_id"                      BIGINT NOT NULL,
    "title"                          TEXT NOT NULL DEFAULT '',
    "rights1"                        BIGINT NOT NULL DEFAULT 0,
    "rights2"                        BIGINT NOT NULL DEFAULT 0,
    "role_id"                        BIGINT NOT NULL DEFAULT 0,
    "boss_id"                        BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY ("empire_id", "avatar_id")
);
