CREATE TABLE IF NOT EXISTS "b_SimTimeAnchor" (
    "id"                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "system_auid"           BIGINT,
    "system_name"           TEXT,
    "anchor_ms"             BIGINT,
    "captured_wallclock_ms" BIGINT,
    "total_dist_sum_au"     DOUBLE PRECISION,
    "optimized_for_auid"    BIGINT,
    "optimized_for_name"    TEXT,
    "source"                TEXT,
    "note"                  TEXT
);
