CREATE TABLE IF NOT EXISTS "b_GalaxyGen" (

    "id"                             BIGINT PRIMARY KEY CHECK ("id" = 1),
    "galaxy_name"                    TEXT NOT NULL,
    "galaxy_number"                  INTEGER NOT NULL,

    "created"                        BIGINT NOT NULL,

    "tool"                           TEXT
);

CREATE TABLE IF NOT EXISTS "g_KnownEmpire" (

    "knower_empire_id"               BIGINT NOT NULL,
    "known_empire_id"                BIGINT NOT NULL,

    "first_met_ms"                   BIGINT NOT NULL,
    "last_seen_ms"                   BIGINT NOT NULL,

    "stance"                         INTEGER DEFAULT 0,

    "tribute"                        INTEGER DEFAULT 0,
    PRIMARY KEY ("knower_empire_id", "known_empire_id")
);

CREATE TABLE IF NOT EXISTS "g_KnownEmpireDoc" (
    "knower_empire_id"               BIGINT,
    "known_empire_id"                BIGINT,

    "doc_idx"                        INTEGER,

    "doc_type"                       INTEGER,

    "timestamp_ms"                   BIGINT,

    "actor_avatar_id"                BIGINT,
    "actor_empire_id"                BIGINT,
    "text_a"                         TEXT,
    "text_b"                         TEXT,
    "text_c"                         TEXT,

    "doc_state"                      INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "hz_chat_log" (

    "id"                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    "ts"                             BIGINT NOT NULL,
    "channel"                        TEXT NOT NULL,

    "sender_auid"                    BIGINT NOT NULL,

    "sender_name"                    TEXT NOT NULL,
    "text"                           TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "hz_native_home" (

    "id"                             BIGINT PRIMARY KEY,

    "world_auid"                     BIGINT NOT NULL,

    "label"                          TEXT,
    "homeX"                          DOUBLE PRECISION,
    "homeY"                          DOUBLE PRECISION,
    "homeZ"                          DOUBLE PRECISION,

    "heading"                        DOUBLE PRECISION,

    "tilt"                           DOUBLE PRECISION
);

CREATE INDEX IF NOT EXISTS "ix_hz_native_home_world" ON "hz_native_home" ("world_auid");

CREATE TABLE IF NOT EXISTS "hz_native_reputation" (

    "world_auid"                     BIGINT NOT NULL,
    "player_auid"                    BIGINT NOT NULL,

    "rep"                            INTEGER NOT NULL,

    "timeModified"                   BIGINT,
    PRIMARY KEY ("world_auid", "player_auid")
);

CREATE TABLE IF NOT EXISTS "hz_native_village" (

    "world_auid"                     BIGINT PRIMARY KEY,

    "auid_block"                     INTEGER NOT NULL,

    "seed"                           BIGINT,
    "pop"                            INTEGER,

    "dna"                            BYTEA,
    "centreX"                        DOUBLE PRECISION,
    "centreY"                        DOUBLE PRECISION,
    "centreZ"                        DOUBLE PRECISION,

    "timeCreate"                     BIGINT,
    "timeModified"                   BIGINT
);

CREATE TABLE IF NOT EXISTS "names" (

    "kind"                           TEXT NOT NULL,

    "auid"                           BIGINT NOT NULL,
    "name"                           TEXT,
    PRIMARY KEY ("kind", "auid")
);

CREATE INDEX IF NOT EXISTS "ix_names_auid" ON "names" ("auid");

CREATE TABLE IF NOT EXISTS "z_StaticTablesSent" (

    "client"                         TEXT PRIMARY KEY,

    "sent_at"                        BIGINT
);

ALTER TABLE "a_Sector"           ADD COLUMN IF NOT EXISTS "parent_atom" BIGINT;
ALTER TABLE "a_SolarSystem"      ADD COLUMN IF NOT EXISTS "parent_atom" BIGINT;
ALTER TABLE "a_Star"             ADD COLUMN IF NOT EXISTS "parent_atom" BIGINT;
ALTER TABLE "a_WorldGlobe"       ADD COLUMN IF NOT EXISTS "parent_atom" BIGINT;
ALTER TABLE "a_WorldGasGiant"    ADD COLUMN IF NOT EXISTS "parent_atom" BIGINT;
ALTER TABLE "a_WorldRing"        ADD COLUMN IF NOT EXISTS "parent_atom" BIGINT;
ALTER TABLE "a_WorldRingSection" ADD COLUMN IF NOT EXISTS "parent_atom" BIGINT;
ALTER TABLE "a_Galaxy"           ADD COLUMN IF NOT EXISTS "parent_atom" BIGINT;
ALTER TABLE "a_Universe"         ADD COLUMN IF NOT EXISTS "parent_atom" BIGINT;

CREATE INDEX IF NOT EXISTS "ix_a_Star_parent_atom"             ON "a_Star" ("parent_atom");
CREATE INDEX IF NOT EXISTS "ix_a_WorldGlobe_parent_atom"       ON "a_WorldGlobe" ("parent_atom");
CREATE INDEX IF NOT EXISTS "ix_a_WorldGasGiant_parent_atom"    ON "a_WorldGasGiant" ("parent_atom");
CREATE INDEX IF NOT EXISTS "ix_a_WorldRing_parent_atom"        ON "a_WorldRing" ("parent_atom");
CREATE INDEX IF NOT EXISTS "ix_a_WorldRingSection_parent_atom" ON "a_WorldRingSection" ("parent_atom");
CREATE INDEX IF NOT EXISTS "ix_a_SolarSystem_parent_atom"      ON "a_SolarSystem" ("parent_atom");
CREATE INDEX IF NOT EXISTS "ix_a_Sector_parent_atom"           ON "a_Sector" ("parent_atom");

ALTER TABLE "a_Universe"      ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;
ALTER TABLE "a_Galaxy"        ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;
ALTER TABLE "a_Sector"        ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;
ALTER TABLE "a_SolarSystem"   ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;
ALTER TABLE "a_Star"          ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;
ALTER TABLE "a_WorldGlobe"    ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;
ALTER TABLE "a_WorldGasGiant" ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;
ALTER TABLE "a_Person"        ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;
ALTER TABLE "g_Empire"        ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;
ALTER TABLE "a_Designer"      ADD COLUMN IF NOT EXISTS "raw_blob" BYTEA;

ALTER TABLE "a_Person" ADD COLUMN IF NOT EXISTS "max_hp"      INTEGER;
ALTER TABLE "a_Person" ADD COLUMN IF NOT EXISTS "max_stamina" INTEGER;
ALTER TABLE "a_Person" ADD COLUMN IF NOT EXISTS "max_hunger"  INTEGER;

ALTER TABLE "a_Bd" ADD COLUMN IF NOT EXISTS "cstateBlob" BYTEA;

ALTER TABLE "a_City" ADD COLUMN IF NOT EXISTS "sim_state" TEXT;

ALTER TABLE "g_Empire" ADD COLUMN IF NOT EXISTS "war_criteria" BYTEA;
